In [19]:
import pandas as pd

# Series one Column of DataFrame

s1 = pd.Series([23, 234, 324, 343])

s2 = pd.Series({
    "Name" : 'Ram', "Brother" : 'Shayam'
})



# Data Frame 

df1 = pd.DataFrame([1, 2, 3, 4], columns = ["Numbers"])

df2 = pd.DataFrame({
    "Age" : [42, 12, 62, 32],
    "Salary" : [10000, 200, 300000, 4000000]
})

In [20]:
s1

0     23
1    234
2    324
3    343
dtype: int64

In [21]:
s2

Name          Ram
Brother    Shayam
dtype: object

In [22]:
df1

   Numbers
0        1
1        2
2        3
3        4

In [23]:
df2

   Age   Salary
0   42    10000
1   12      200
2   62   300000
3   32  4000000

In [24]:
# Data Frame By Series Un Equal Seies

data = pd.DataFrame({
    "Name" : s1,
    "Age" : s2
})
data

          Name     Age
0         23.0     NaN
1        234.0     NaN
2        324.0     NaN
3        343.0     NaN
Brother    NaN  Shayam
Name       NaN     Ram

In [25]:
# Data Frame By Series
s1 = pd.Series(["Ram", "Shyam", "GhanShyam"])
s2 = pd.Series([10, 12, 14])

data = pd.DataFrame({
    "Name" : s1,
    "Age" : s2
})
data

        Name  Age
0        Ram   10
1      Shyam   12
2  GhanShyam   14