In [1]:
import pandas as pd

In [16]:
df = pd.read_csv(r"E:\DATA FOR TEST\Tele Customer churn\WA_Fn-UseC_-Telco-Customer-Churn _1.csv")
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors = 'coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            6988 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            6742 non-null   float64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(3), int64(1), object(17)
memory usage: 1.1+ MB

In [26]:
# Gender Group by Total Charges by Sum 
df.groupby('gender')["TotalCharges"].sum()

gender
Female    7878473.4
Male      8049553.9
Name: TotalCharges, dtype: float64

In [27]:
# Gender Group by Total Charges by mean
df.groupby('gender')["TotalCharges"].mean()

gender
Female    2280.970874
Male      2284.857763
Name: TotalCharges, dtype: float64

In [29]:
# Gender Group by Total Charges by Median
df.groupby('gender')["TotalCharges"].median()

gender
Female    1384.725
Male      1404.650
Name: TotalCharges, dtype: float64

In [30]:
# Gender Group by Total Charges by Minimum
df.groupby('gender')["TotalCharges"].min()

gender
Female    18.85
Male      18.80
Name: TotalCharges, dtype: float64

In [31]:
# Gender Group by Total Charges by Maximum
df.groupby('gender')["TotalCharges"].max()

gender
Female    8672.45
Male      8684.80
Name: TotalCharges, dtype: float64

In [34]:
# Gender Group by Count of All Variable
df.groupby('gender').count()

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
gender,,,,,,,,,,,,,,,,,,,,
Female,3459,3459,3459,3459,3334,3459,3459,3459,3459,3459,3459,3459,3459,3459,3459,3459,3459,3459,3454,3459
Male,3529,3529,3529,3529,3408,3529,3529,3529,3529,3529,3529,3529,3529,3529,3529,3529,3529,3529,3523,3529

In [44]:
# tenure Group by Count of All Variable
df.groupby('tenure').count()

,customerID,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
tenure,,,,,,,,,,,,,,,,,,,,
0.0,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0,11
1.0,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581
2.0,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226
3.0,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193
4.0,171,171,171,171,171,171,171,171,171,171,171,171,171,171,171,171,171,171,171,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68.0,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98
69.0,91,91,91,91,91,91,91,91,91,91,91,91,91,91,91,91,91,91,91,91
70.0,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117
71.0,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161
72.0,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345