In [9]:
import pandas as pd

In [10]:
df_csv = pd.read_csv(r"E:\DATA FOR TEST\50 Startups\50_Startups.csv")
df_csv.head(3)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39

In [12]:
df_excel = pd.read_excel(r"E:\DATA FOR TEST\NEW START.xlsx")
df_excel.tail(2)

,hotel,is_canceled,arrival_date_year,arrival_date_month,adults,children,babies,country,reserved_room_type,assigned_room_type,reservation_status,reservation_status_date,Room Status,Guest_type
119388,City Hotel,0,2017,August,2,0.0,0,GBR,A,A,Check-Out,2017-09-07,Desired,Couple
119389,City Hotel,0,2017,August,2,0.0,0,DEU,A,A,Check-Out,2017-09-07,Desired,Couple

# Exporting / Saving Data

In [17]:
# Save data by Variable in Excel Formate 
df_excel.to_csv("Clean_data.csv")

# Save data by Variable in Comma Separated Variable (CSV)
df_csv.to_excel("Clean_data.xlsx")

# We Can Provide Path Where To Save File