In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"E:\DATA FOR TEST\50 Startups\50_Startups.csv")
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [11]:
# Shape of Data In (Rows, Columns)
df.shape

(50, 5)

In [13]:
# All Columns Name
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [6]:
# Count, Mean, Standard Deviation, Minimum, Maximum, 25, 50, 75 Percentile Of Numerical Data 
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [7]:
# Data Type, null Count, Column Name Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [15]:
# Value Counts of Columns
df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [20]:
# Unique Values in Column
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [21]:
# Total Unique Values in Column
df['State'].nunique()

3

In [27]:
df.nunique()

R&D Spend          49
Administration     50
Marketing Spend    48
State               3
Profit             50
dtype: int64

In [32]:
# Data Duplicated Values Sum
df['State'].duplicated().sum()

47